name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Check
      run: cargo check --verbose
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Format
      run: cargo fmt --all -- --check --verbose
    - name: Install clippy
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy -- -D warnings --verbose
    - name: Test
      run: cargo test --verbose
